name: Spell-Checker

on:
  push:
    branches:
      - main

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run spell checker
        run: node public/spell-checker.js
