name: HTML-Validation

on:
  push:
    branches:
      - main

jobs:
  html-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install html-validate
        run: npm install -g @html-validate/cli

      - name: Run html-validate
        run: html-validate .

      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: html-validation-report
          path: html-validate-report.html
